### ISSUE TITLE
How to use latest allkeys.txt

### ISSUE THREAD

**Issue by santhoshtr** [jtauber/pyuca#10]
It would be nice if the alkeys.txt is not hard coded to particular version and able to supply a latest one to library, such as from http://www.unicode.org/Public/UCA/latest/allkeys.txt

**Comment by jtauber** [comment]
It's not hard-coded. You can give Collator() an optional filename of the collation element table to use.

**Comment by santhoshtr** [comment]
Yeah, I saw that. But the default allkeys comes with this is 6.3.0. So I tried to update it to 10.0.0  in my forked branch https://github.com/santhoshtr/pyuca/tree/10.0.0

The tests gives me this result:
197989 success; 64 failure (UCA version 10.0.0)

I will check if this can be improved

**Comment by jtauber** [comment]
What version of Python are you testing on? There may be limitations on what UCA version can be supported by a particular Python version (which is why two allkeys.txt were shipped).

It would be great if pyuca shipped with the latest allkeys supported by the latest Python version so it would be great to find out what that is.

**Comment by santhoshtr** [comment]
> What version of Python are you testing on?

Python 3.5

**Comment by jtauber** [comment]
I'll reopen this issue with the goal of evaluating whether we can ship with a later version of allkeys for some newer versions of Python.

**Comment by jtauber** [comment]
I believe 3.6 is 9.0.0 so we COULD ship with 9.0.0 with a test for Python 3.6 I think

**Comment by jtauber** [comment]
3.5 seems to be 8.0.0 so we could try the 8.0.0 allkeys for 3.5

**Comment by jtauber** [comment]
Note that not only allkeys but the test files need to be updated as well as a new Collator class for each version.

**Comment by santhoshtr** [comment]
> 3.5 seems to be 8.0.0

You mean the unicodedata comes with Unicode database 8.0.0. I was not aware of this dependency. Now got it.

> Note that not only allkeys but the test files need to be updated as well as a new Collator class for each version.

Yes, I am refering the UCA test data provided at http://unicode.org/reports/tr10/#Tests10

**Comment by jtauber** [comment]
I've started a branch for getting things working with 8.0.0, 9.0.0, and 10.0.0

**Comment by jtauber** [comment]
Looks like I need to implement @implicitweights so I've created #12 for that and will work on that now

**Comment by jtauber** [comment]
8.0.0 added U+9FCD through U+9FD5 as CJK UNIFIED IDEOGRAPHS

**Comment by jtauber** [comment]
Okay, I have everything working for 8.0.0 and 9.0.0 and will do a PR shortly. Before I do a release, @santhoshtr it would be great if you tested it for your use case.

**Comment by jtauber** [comment]
@santhoshtr PR #13 is available for testing before I merge and release.

**Comment by santhoshtr** [comment]
@jtauber Looks good to me. Tested. I left comment about duplicated test there

**Comment by jtauber** [comment]
Okay, I omitted the duplicated test. If the tests all pass, I'll mere the PR.

**Comment by jtauber** [comment]
merged! I'll do a release after I get some sleep. Thanks for your help @santhoshtr !
