### ISSUE TITLE
Python 2.7 support

### ISSUE THREAD

**Issue by pmclanahan** [jtauber/pyuca#3]
I made some [changes in my fork](https://github.com/pmclanahan/pyuca/commit/43eb0a0666b4e5cfe0c4628e480cbb137530d0c0) to support Python 2.7. I didn't do the work to make it a single 2 and 3 codebase yet, but I think it'd be very easy since the changes to make it work on 2 alone were very minimal. Would you be open to a PR for that, or is this Python 3 only and you'd like it to stay that way?

**Comment by debdattaen** [comment]
@SmileyChris are you interested in releasing your fork https://github.com/SmileyChris/pyuca to pypi?

**Comment by debdattaen** [comment]
@SmileyChris  the one you have supports 2 and 3 both, so I guess something more generic? :) Having your stuff in pypi would be awesome!

**Comment by nijel** [comment]
Definitely sounds like a good idea, best if @jtauber could approve this change.

**Comment by jtauber** [comment]
@SmileyChris can you do a pull request (or is it the same as @nijel's #4?) ?

I should be able to review it in the next day or so and merge and release.

**Comment by jtauber** [comment]
@SmileyChris oh, and make sure the AUTHORS files properly credits you and anyone else.

**Comment by nijel** [comment]
@jtauber It should be same, I've just updated Travis setup and fixed doctests on top of that.

**Comment by SmileyChris** [comment]
@nijel did a rebase which makes the commits look a bit dirty, but the only changes were indeed his small test fixes.

**Comment by jtauber** [comment]
@SmileyChris @nijel @pmclanahan merged and released as 1.1! Thanks for all your work

**Comment by debdattaen** [comment]
Thanks all!
